---
title: "WW-12_Diff&Int"
author: "Clay Wright"
format: html
---

#Week 12 - Differentiation & Integration
Now that we've got some tools from earlier in this semester, we're going to focus on differentiation & integration. Specifically, we will look at examples that apply these calculus methods to real life scenarios. This topic will be particularly useful in future job positions. Being able to automate workflows that can quickly load data and analyze rates & variable relationships has normalized educated & efficient decision-making in the workplace. 

There will first be a differentiation problem & then an integration problem - that integrates in 2 ways. We'll use mathematical integration to quantify mass/volume under a curve. If you have mass/time on the y-axis, and time on the x-axis, then you can integrate under the observational points & obtain the total mass that has passed through or accumulated in a system over a specific time period.

We'll start the HW assignment in class - it's more like a case-study this week. You'll draw on previous content you've learned, and use a new function for integration - trapz again from the pracma package. 

#Biggest takeaway - workflow
The biggest thing I want you to get out of this week: workflow. That is, think about how you are going to accomplish this problem, break it down into steps, and then implement those steps.

```{r setup}
library(pracma)

```
